# Generated by Django 5.2.6 on 2025-10-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='preco_aluguel',
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='listing_type',
            field=models.CharField(choices=[('COLEGA', 'Colega de quarto'), ('REPUBLICA', 'República')], default='COLEGA', max_length=20),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_banheiros',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_quartos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_varandas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_cobranca',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=10),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('KITNET', 'Kitnet')], default='APARTAMENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_imoveis/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='imoveis.tag'),
        ),
    ]
