# Generated by Django 5.2.6 on 2025-10-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_tag_alter_imovel_options_remove_imovel_preco_aluguel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='numero_varandas',
            new_name='numero_garagens',
        ),
    ]
