# Generated by Django 5.2.7 on 2025-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0003_conversationusermeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationusermeta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
