# Generated by Django 4.2.11 on 2025-10-06 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('kitnet', 'Kitnet'), ('republica', 'República')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('quartos', models.IntegerField(default=1)),
                ('banheiros', models.IntegerField(default=1)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mobiliado', models.BooleanField(default=False)),
                ('aceita_pets', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('estacionamento', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='propriedades/')),
                ('principal', models.BooleanField(default=False)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propriedades.propriedade')),
            ],
        ),
    ]
