# Generated by Django 4.2.11 on 2025-10-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
