# Generated by Django 5.0.4 on 2025-10-18 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_alter_propriedade_endereco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='propriedades_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fotopropriedade',
            name='imagem',
            field=models.FileField(upload_to='propriedades/'),
        ),
    ]
