# Generated by Django 5.0.4 on 2025-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0003_propriedade_favoritos_alter_fotopropriedade_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
