# Generated by Django 5.2.7 on 2025-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0011_add_status_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosolicitacao',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('paid', 'Pago')], default='pending', max_length=20),
        ),
    ]
