version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      - db

  web:
    build:
      context: ../web
      dockerfile: ../infra/Dockerfile.web
    volumes:
      - ../web:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quartinho_ps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
