# Generated by Django 5.2.7 on 2025-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_imovel_imovel_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel_foto',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='imovel_foto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis_fotos/'),
        ),
    ]
