# Generated by Django 5.0.4 on 2025-10-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preference',
            field=models.CharField(blank=True, choices=[('roommate', 'Procurando colega de quarto'), ('room', 'Procurando quarto')], max_length=20, null=True),
        ),
    ]
