# Generated by Django 5.2.7 on 2025-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('kitnet', 'Kitnet')], default='casa', max_length=20),
        ),
    ]
