# Generated by Django 5.0.4 on 2025-10-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_imovel_tipo'),
        ('usuarios', '0006_usuario_preference'),
    ]

    operations = [
    ]
