# Generated by Django 5.0.4 on 2025-10-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_0006_imovel_tipo_0006_usuario_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel_foto',
            name='imovel',
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/'),
        ),
        migrations.DeleteModel(
            name='Imovel',
        ),
        migrations.DeleteModel(
            name='Imovel_Foto',
        ),
    ]
