# Generated by Django 5.0.4 on 2025-10-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_0006_imovel_tipo_0006_usuario_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel_foto',
            name='imovel',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Imovel',
        ),
        migrations.DeleteModel(
            name='Imovel_Foto',
        ),
    ]
